### ISSUE TITLE
Nitro only returns userID on profile request

### ISSUE THREAD

**Issue by harb00** [80O/PlusEMU#141]
**Describe the bug**
Nitro only returns userID on profile request but the server expects a boolean also and will crash on OpenPlayerProfileEvent

**To Reproduce**
1. Search for any user
2. Click on their profile
3. See error

**Expected behavior**
Show their profile without crashing the server

**Emulator Error**
```csharp
Plus.Communication.Packets|Error handling packet "OpenPlayerProfileEvent" for session 00000000-0000-0000-0000-000000000000 @ Habbo  "Admin": "Specified argument was out of the range 
of valid values." "   at Plus.Communication.Flash.FlashIncomingPacket.ReadInt() in C:\vscodeProjects\PlusEMU\Communication\Flash\FlashIncomingPacket.cs:line 38
   at Plus.Communication.Flash.FlashIncomingPacket.ReadBool() in C:\vscodeProjects\PlusEMU\Communication\Flash\FlashIncomingPacket.cs:line 45
   at Plus.Communication.Packets.Incoming.Users.OpenPlayerProfileEvent.Parse(GameClient session, IIncomingPacket packet) in C:\vscodeProjects\PlusEMU\Communication\Packets\Incoming\Users\OpenPlayerProfileEvent.cs:line 22"```

**Comment by 80O** [comment]
If nitro doesnt comply with the flash client, report it to the Nitro devs.
