### ISSUE TITLE
[Nitro 1.3.4] Lagg when opening Achievements progress box

### ISSUE THREAD

**Issue by matotubol** [80O/PlusEMU#143]
**Describe the bug**
Whenever you open the achievement progress box you will start lagging

**To Reproduce**
1. Go to your room
2. Click on achievemnts and choose 1 progress achievement and click on in
3. start to walk in your room while having the achievement progress opened and you will see the lagg it dissapears when you close the dialog

**Screenshots**
(https://gyazo.com/f0147531f6b8aaf83c713ed77871c838)

**Browser Console Error**
There is no error.

**Emulator Error**
Sometimes i get this error and sometimes no error just lagg.
```
2022-08-05 08:32:51.1932|ERROR|Plus.Communication.Packets|Error handling packet "OpenPlayerProfileEvent" for session 00000000-0000-0000-0000-000000000000 @ Habbo  "mato": "Specified argument was out of the range of valid values." "   at Plus.Communication.Flash.FlashIncomingPacket.ReadInt() in C:\Users\Matob\Documents\PlusEMU-master\Communication\Flash\FlashIncomingPacket.cs:line 38
   at Plus.Communication.Flash.FlashIncomingPacket.ReadBool() in C:\Users\Matob\Documents\PlusEMU-master\Communication\Flash\FlashIncomingPacket.cs:line 45
   at Plus.Communication.Packets.Incoming.Users.OpenPlayerProfileEvent.Parse(GameClient session, IIncomingPacket packet) in C:\Users\Matob\Documents\PlusEMU-master\Communication\Packets\Incoming\Users\OpenPlayerProfileEvent.cs:line 22"
```

**Nitro version 1.3.4**

**Comment by 80O** [comment]
Does this also happen on the flash client? If not this is a nitro bug which should be reported to the nitro developers instead.

**Comment by matotubol** [comment]
On Flash it works as intended so its an Nitro issue.

**Comment by 80O** [comment]
Closed. Please report to the nitro devs as it seems to be a nitro issue.
